# Generated by Django 3.0.8 on 2020-11-30 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Name', max_length=150, validators=[django.core.validators.MinLengthValidator(2, 'The name must be more than 1 character')])),
                ('last_name', models.CharField(help_text='Enter a Last name', max_length=150, validators=[django.core.validators.MinLengthValidator(2, 'The name must be more than 1 character')])),
                ('id_type', models.CharField(help_text='Enter a ID Type', max_length=150)),
                ('id_number', models.IntegerField(default=0, help_text='Enter a ID Number')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.CharField(help_text='Enter a User', max_length=150)),
                ('state', models.BooleanField(default=True)),
                ('password', models.CharField(help_text='Enter a Password', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
